### ISSUE TITLE
bbb-api show offline

### ISSUE THREAD

**Issue by genikarimi** [greenstatic/bigbluebutton-exporter#101]
hi 
everything is okay and few rooms created but show  zero Participants and api offline
im on single localhost and running  bbb 2.3.11
thanks
![Capture](https://user-images.githubusercontent.com/67128542/133943953-f9e70b0a-55d6-41d3-a01d-cffdf056e07e.PNG)
s

**Comment by greenstatic** [comment]
1. How did you install the exporter?
2. What does the exporter return (`curl http://<ip>:<port>/metrics`)?
3. Are you sure the API secret is correct?

**Comment by etherz10** [comment]
@greenstatic I'm having a similar problem on multiple 2.4.7 machines.

I'm running both node_exporter and bbb-exporter via docker and my Prometheus instance is able to scrap both of them but I'm getting `bbb_api_up 0.0`

I turned on debug mode and looking in the logs of the bbb-exporter container I can see the following.

```
bbb-exporter    | 2022-05-20 09:17:51,265 [DEBUG]: Requesting via API recordings deleted data
bbb-exporter    | 2022-05-20 09:17:51,265 [DEBUG]: TLS CA verification is enabled for API call
bbb-exporter    | 2022-05-20 09:17:51,266 [DEBUG]: Starting new HTTPS connection (1): BBBHOST:443
bbb-exporter    | 2022-05-20 09:17:51,266 [ERROR]: Failed to perform API call
bbb-exporter    | 2022-05-20 09:17:51,266 [ERROR]: HTTPSConnectionPool(host='BBBHOST', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=73f8b499807ebabc769a78aa3a9f5effb182782f&state=deleted (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c9a537dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
bbb-exporter    | 2022-05-20 09:17:51,266 [DEBUG]: Calculating room participants histogram
bbb-exporter    | 2022-05-20 09:17:51,267 [DEBUG]: Calculating room listeners histogram
bbb-exporter    | 2022-05-20 09:17:51,267 [DEBUG]: Calculating room voice participants histogram
bbb-exporter    | 2022-05-20 09:17:51,267 [DEBUG]: Calculating room video participants histogram
bbb-exporter    | 2022-05-20 09:17:51,267 [INFO]: Finished collecting metrics from BigBlueButton API
```

The weird thing is if I call that same URL locally from my local machine I get a response...

```
<response>
<returncode>SUCCESS</returncode>
<recordings/>
<messageKey>noRecordings</messageKey>
<message>There are no recordings for the meeting(s).</message>
</response>
```

This would indicate the secret is correct but some weird routing issue to itself?

Are you able to assist as this is driving me mad?

**Comment by greenstatic** [comment]
Could be a DNS issue, checkout this: https://github.com/greenstatic/bigbluebutton-exporter/pull/85

**Comment by greenstatic** [comment]
@genikarimi were you able to figure it out?

**Comment by etherz10** [comment]
@greenstatic Ah thanks so much, that resolved my issue. 🍰
