### ISSUE TITLE
nginx not found

### ISSUE THREAD

**Issue by secretreal26** [greenstatic/bigbluebutton-exporter#11]
Hi,

I try to install but got error :

850 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: demo-bbb.xxxxxx.com, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "demo-bbb.xxxxxx.net"

Am I miss sth?

Regards,

CK

**Comment by greenstatic** [comment]
I presume you are getting this from your nginx error logs? Are you sure you are running the exporter on the same server on localhost (127.0.0.1) port 9688? 

Check using: `sudo docker ps`, do you see the exporter running?
Try on the server `curl http://127.0.0.1:9688/metrics` - you should be getting the raw metrics in the prometheus format.

**Comment by greenstatic** [comment]
I'm closing this for now, if the issue persists you are welcome to reopen the issue.
