### ISSUE TITLE
bbb-exporter gets timeout on BBB2.5

### ISSUE THREAD

**Issue by makabar** [greenstatic/bigbluebutton-exporter#111]
I´ve installed a fresh BBB2.5.
Followed all instructions as recommended.
While starting by `docker-compose up`
i get this error:
`bbb-exporter    | 2022-06-10 09:01:37,255 [ERROR]: HTTPSConnectionPool(host='bbb3.meinebbburl.de', port=443): Max retries exceeded with url: /bigbluebutton/api/getMeetings?checksum=checkcheckcheckcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f62f0a66a90>: Failed to establish a new connection: [Errno 110] Operation timed out'))`
The Checksum is right. I can call the getMeetings API with my desktop-browser

**Comment by greenstatic** [comment]
Check this: https://github.com/greenstatic/bigbluebutton-exporter/pull/85

**Comment by makabar** [comment]
> Check this: #85

Worked for me! Thanks!
