### ISSUE TITLE
container won't start with docker v23

### ISSUE THREAD

**Issue by fireba11** [greenstatic/bigbluebutton-exporter#117]
It seems several containers from different projects got issues with latest docker version ...

ERROR: for bbb-exporter  Cannot start service bbb-exporter: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown

Docker version 23.0.1, build a5ee5b1

**Comment by greenstatic** [comment]
Which version (i.e. tag) of the image are you running?

**Comment by fireba11** [comment]
v0.6.0
The issue was caused by a missing apparmor package on the bbb server. Apparently that is required by docker now for certain containers but doesn't get pulled as dependency.
