### ISSUE TITLE
[2.6-rc3] Metrics stopped working.

### ISSUE THREAD

**Issue by JeanPluzo** [greenstatic/bigbluebutton-exporter#118]
Issue posted originally in [bigbluebutton/bigbluebutton](https://github.com/bigbluebutton/bigbluebutton/issues/16728)
If further info is needed I'll be glad to provide it.

Regards,
J.

**Comment by Wladimir-N** [comment]
https://github.com/greenstatic/bigbluebutton-exporter/pull/116

**Comment by greenstatic** [comment]
Could you try the Docker image `greenstatic/bigbluebutton-exporter:v0.6.1-preview1`? It is a preview build of #116.

**Comment by JeanPluzo** [comment]
Hi,
just tested the `v0.6.1-preview1` image.
Errors:
`bbb-exporter   | exec /usr/local/bin/python: exec format error`
`bbb-exporter exited with code 0`
`bbb-exporter exited with code 1`
`bbb-exporter exited with code 1`
`bbb-exporter exited with code 1`
and `docker container ls -a` shows `STATUS restarting (1) x seconds ago`
But thanks for the update!

**Comment by JeanPluzo** [comment]
Just noticed something: the image you wrote before (`v0.6.1-preview1`) is for arm64. I have the bbb-exporter installed on an Ubuntu 20.04 Server, which is amd64.
Do you have an image for the amd64 architecture?
This may be the cause of the previous errors.

**Comment by greenstatic** [comment]
Ahh, completely forgot, I recently switched from an Intel Mac to an Apple Silicon one. 😅 Will make a build for amd64.

**Comment by greenstatic** [comment]
Try now. Pull the same tag again: `docker pull greenstatic/bigbluebutton-exporter:v0.6.1-preview1`

**Comment by JeanPluzo** [comment]
Container doesn't restart. `docker compose up -d` throws no errors. Grafana shows all metrics for my 2.6 Server.
I think it's fixed. Thanks!
If I see anything else I'll post here.
Are you going to change the name from `v0.6.1-preview1` to something else? I'm asking because I want to post this image/solution in the bigbluebutton issues right away, but I'll wait if you're planning on changing the image name.

**Comment by greenstatic** [comment]
The release is available as Docker image tag [v0.6.1](https://hub.docker.com/layers/greenstatic/bigbluebutton-exporter/v0.6.1/images/sha256-9d9554c5d81575af7c04b2698d6c2fcf2be92bad1faddc489c2b43ca11156629?context=explore).

Thank you all for helping solve this issue.
