### ISSUE TITLE
Update of xmltodict breaks exporter

### ISSUE THREAD

**Issue by tibroc** [greenstatic/bigbluebutton-exporter#128]
The update of the `xmltodict`-dependency (0.12.0 -> 0.13.0) breaks the exporter due to dropping `OrderedDict` support (see https://github.com/martinblech/xmltodict/commit/231b4d4ef4e804ca0311182e8ec8874af98a1bb7).

This breaks filtering for `OrderectDict` here: https://github.com/greenstatic/bigbluebutton-exporter/blob/master/bbb-exporter/api.py#L32 and here: https://github.com/greenstatic/bigbluebutton-exporter/blob/master/bbb-exporter/api.py#L69

Because of that the exporter will show 0s everywhere.

I might be able to provide a fix later.

**Comment by greenstatic** [comment]
Thanks for your help.
Just made the release: https://github.com/greenstatic/bigbluebutton-exporter/releases/tag/v0.7.1
