### ISSUE TITLE
Instance name empty

### ISSUE THREAD

**Issue by thoschi** [greenstatic/bigbluebutton-exporter#14]
I am not sure if this is an error or just my non-existing experience with prometheus/netdata.

I followed the installation procedure and i could see the server when choosing the "all servers" dashboard. However the server instance showed nothing as the "instance" field on top of the dashboard was empty. I could add there my server manually though. Even then I did not get any CPU values, just the bbb values (number of users/video/...).

Then I checked the settings for the Dashboard and found the settings for `variables`. There the value for `refresh` was set to `never`. After changing it to `on dashboard load` everything worked as expected (and shown in the screenshots).

Maybe I did something wrong as I wonder why no one else seems to have this problem. If not it would probably help to mention this in the installation notes or change the json file (see #13).

Anyway thank you for an awesome tool!

Thomas

**Comment by greenstatic** [comment]
Your PR is good, thank you for it :) and 👏 for finding and sharing the proper solution.

I'm just curious, did you import the Grafana dashboard before you added Prometheus as a data source? That would explain why Grafana failed to fetch the variable values and then didn't try to request them again.

**Comment by thoschi** [comment]
Wow thats a quick response :-)

And you are right - this might be the reason. I imported the dashboard first, as I had no prometheus at all at this point. And I was really stumbling through all this as I had no prometheus/grafana running at all. I tried to reimport the json later though (as I thought that this might be the reason) but it did not help though.

Maybe you could add a hint somewhere that **if** someone installs grafana on the bbb-server itself, the standard port 3000 is already used by the new bbb-html5-client (`/etc/bigbluebutton/nginx/bbb-html5.nginx`). So I needed to change the port to something else in `/etc/grafana/grafana.ini`.

Thank you for your work - its just amazing to see how OpenSource works!

Best regards
Thomas

**Comment by greenstatic** [comment]
Hehe, this is open source, we either fix it immediately or in a years time 😆 

Really good tip regarding the Grafana installation on the same server. I would be thrilled if you could add that to the README.md and make a PR. Otherwise I'll do it a bit later. :)

**Comment by greenstatic** [comment]
Closed by #15
