### ISSUE TITLE
Cannot run docker-compose - python not found

### ISSUE THREAD

**Issue by krim404** [greenstatic/bigbluebutton-exporter#16]
i cannot start the bbb-exporter docker container.

> Status: Downloaded newer image for greenstatic/bigbluebutton-exporter:v0.2.0
> Creating bbb-exporter ... error
> 
> ERROR: for bbb-exporter  Cannot start service bbb-exporter: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown

**Comment by greenstatic** [comment]
I think this is a docker-compose issue. You are probably running this on Ubuntu 18.04 LTS or similar since afaik they do not sym link `python` to python2 or python3. You can confirm this by running `python --version` in the shell. If you get a command not found or similar error this confirms my suspicion.

The best course of action to take is to manually create a symbolic link python -> python3:

```bash
sudo ln -s /usr/bin/python3 /usr/bin/python
```

**Comment by wmchris** [comment]
python is installed. as far as i can see this error is from within the docker instance.
> root@bbb:~/bbb-exporter# python --version
> Python 2.7.12

**Comment by greenstatic** [comment]
The container image should be okay, since you are the first to report this issue.

Can you confirm you can run the following:
```bash
docker run --rm python:3.7-stretch python --version
``` 
This is the what the container uses: https://github.com/greenstatic/bigbluebutton-exporter/blob/master/Dockerfile#L1

If it works, then the container should work as well. Try creating the bbb-exporter container manually instead of using docker compose;
```bash
docker run --rm greenstatic/bigbluebutton-exporter:v0.2.0 
```

You should get a KeyError: 'API_BASE_URL' since we didn't supply any environment variables not a:
> "exec: "python": executable file not found in $PATH": unknown

If you get a KeyError then the container works and you have a docker-compose issue.

**Comment by wmchris** [comment]
the python command works, but sadly the docker run bbbexporter does not, same error:

> root@bbb:~/bbb-exporter# docker run --rm greenstatic/bigbluebutton-exporter:v0.2.0 
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

**Comment by greenstatic** [comment]
This is very strange.
Try the following command:
```bash
docker run --rm --entrypoint python3 greenstatic/bigbluebutton-exporter:v0.2.0 
```

**Comment by wmchris** [comment]
same error :-/

**Comment by greenstatic** [comment]
Can you also run
```bash
docker image ls
```
And paste both lines for python and greenstatic/bigbluebutton-exporter.

**Comment by wmchris** [comment]
```
root@bbb:~# docker image ls
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
postgres                             9.5                 92c35e11d59c        2 days ago          197MB
python                               3.7-stretch         adfad110435a        2 days ago          941MB
bigbluebutton/greenlight             v2                  4b4075d493cc        2 weeks ago         198MB
greenstatic/bigbluebutton-exporter   latest              fc3c4ce90c0b        2 weeks ago         950MB
greenstatic/bigbluebutton-exporter   v0.2.0              84fdfb2f6e1a        2 weeks ago         950MB
```

**Comment by greenstatic** [comment]
We are running the exact same python and bbb-exporter docker images. This must be a docker host issue.

Can you specify the following:
1. Which OS you are running and the version
2. Docker version

**Comment by wmchris** [comment]
```
root@bbb:~# docker --version
Docker version 19.03.8, build afacb8b7f0
```

Ubuntu 16.04.6 LTS (GNU/Linux 4.19.0-8-amd64 x86_64)

**Comment by greenstatic** [comment]
We are running the exact same Docker version on the same version on Ubuntu. Here is one of our bbb servers:
```
ubuntu@bbb2:~$ docker --version
Docker version 19.03.8, build afacb8b7f0
ubuntu@bbb2:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
ubuntu@bbb2:~$ sudo docker image ls
REPOSITORY                             TAG                   IMAGE ID            CREATED             SIZE
greenstatic/bigbluebutton-exporter     v0.2.0                84fdfb2f6e1a        2 weeks ago         950MB
bigbluebutton/greenlight               v2                    2adae0c5cc94        6 weeks ago         198MB
postgres                               9.5                   222fd382d72b        6 weeks ago         197MB
ubuntu@bbb2:~$ sudo docker run --rm greenstatic/bigbluebutton-exporter:v0.2.0 
Traceback (most recent call last):
  File "server.py", line 6, in <module>
    import settings
  File "/app/settings.py", line 14, in <module>
    API_BASE_URL = validate_api_base_url(os.environ["API_BASE_URL"])
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'API_BASE_URL'
```

This is definitely some weird host thing.
Can you post the output of:
```bash
ls -l $(which python)
python3 --version
```

**Comment by wmchris** [comment]
```
root@bbb:~/greenlight# ls -l $(which python)
lrwxrwxrwx 1 root root 16 Apr 19 17:19 /usr/bin/python -> /usr/bin/python3
root@bbb:~/greenlight# python3 --version
Python 3.5.2

```

**Comment by greenstatic** [comment]
You better change it back to 2.7 if it was present. Too many system scripts rely on that. In case it wasn't set it wouldn't be such big of an issue to change it.

Did you try any of the previous commands with python->python3 ? If so, retry them.

**Comment by wmchris** [comment]
i did all of them with python2.7 and 3 on two different machines installed at the very exact time of the day. Everything is the same. :/

**Comment by greenstatic** [comment]
Did you change anything on the system? I see this is your bbb (and previously bbb2) host. If you tried on a different system with e.g. Ubuntu 18.04 this shouldnt occur. I'm trying on my mac and on our bbb server and I can't replicate your issue.

How did you install docker?

**Comment by wmchris** [comment]
i didnt change anything on the system, it is a clean ubuntu 16.04 minimal inside a vm and setup  using the bbb-install script.

**Comment by greenstatic** [comment]
It's a shot in the dark, but could you try the docker command with the ubuntu user and not root? You will need to run with sudo.

**Comment by wmchris** [comment]
```
ubuntu@bbb:/root/greenlight$ sudo docker run --rm greenstatic/bigbluebutton-exporter:v0.2.0 
[sudo] password for ubuntu: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.
ERRO[0005] error waiting for container: context canceled 
```

**Comment by greenstatic** [comment]
```bash
docker run --rm --entrypoint /usr/local/bin/python3 greenstatic/bigbluebutton-exporter:v0.2.0 server.py
```

**Comment by wmchris** [comment]
```
ubuntu@bbb:~$ sudo docker run --rm --entrypoint /usr/local/bin/python3 greenstatic/bigbluebutton-exporter:v0.2.0 server.py
[sudo] password for ubuntu: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/python3\": stat /usr/local/bin/python3: permission denied": unknown.
```

**Comment by greenstatic** [comment]
Okay now we are getting a permission error, this is getting stranger the deeper we go.

Override the user of the container to root;
```bash
 sudo docker run --rm --user 0 --entrypoint /usr/local/bin/python3 greenstatic/bigbluebutton-exporter:v0.2.0 server.py
```

**Comment by greenstatic** [comment]
Do you have selinux/apparmor  or anything similar enabled?

**Comment by wmchris** [comment]
yes, apparmor is enabled.

**Comment by greenstatic** [comment]
Did you change your apparmor config besides the defaults?

**Comment by wmchris** [comment]
nope, i'm just starting to set up the server, it is not modified, yet.

**Comment by greenstatic** [comment]
I'll ask around a bit to see what other docker specialist think about this issue in the mean time I suggest you override the user (try first without entrypoint) in the docker-compose file. 

The user `nobody` is standard best practice in the dockerfile so the process doesn't run as root in the container - a security precaution.

**Comment by wmchris** [comment]
ok, i changed the docker-compose and now it is working (as a temporary workaround)

**Comment by greenstatic** [comment]
If you find anything regarding this, do share :smile:  I'm completely stumped what the issue is :thinking:

**Comment by greenstatic** [comment]
Did you by any chance solve the original issue?

**Comment by wmchris** [comment]
no, i didnt have any time to debug the initial issue and continued using the workaround

**Comment by krim404** [comment]
its still the same
