### ISSUE TITLE
Traffic only IPv4

### ISSUE THREAD

**Issue by sbellm** [greenstatic/bigbluebutton-exporter#18]
Hallo together,

i'm using the BBB exporter and my BBB Instance runs IPv4 and IPv6.
In the Charts, only the IPv4 Traffic is shown, in netdata i can see different values!

Thanks for patching.

**Comment by tarunb999** [comment]
@sbellm .. I'm a novice in coding.
Can you  be kind enough to spell in easy steps on how to install BBB exporter(and the accompaniments)  and how much cpu does it eat?
It seems we need to to install Grafana, Prometheus and Netdata .. but in what sequence and in which directories etc?

Thanks for the help.

**Comment by greenstatic** [comment]
@sbellm I'll look into it. Thanks for the report!

**Comment by sbellm** [comment]
For my server, i changed to 
abs(netdata_net_net_kilobits_persec_average{chart="net.eth0", instance="$instance"}), because ipv4 and ipv6 ist bind to eth0.

You can show the ipv6 traffic via netdata_system_ipv6_kiloits_persec_average. that was no problem for me. Adding ipv4 and ipv6 traffic to one chart, that was my problem.

**Comment by greenstatic** [comment]
If you would like ipv4 and ipv6 traffic metrics to be separate, you can just add an additional query to the graph - one for ipv6 and the other for ipv6.

**Comment by sbellm** [comment]
that is no problem, ipv4+ipv6 traffic is the best solution. (Because the client decides to join in v4 or v6 and the traffic is usually on the same network.

**Comment by greenstatic** [comment]
I agree, but I am a bit reluctant on the user having to enter their primary interface (eth0 in your case). I'll look over the netdata metrics to see if there is some other alternative solution. Any other suggestions are welcome/
