### ISSUE TITLE
No data from bbb-exporter in grafana 

### ISSUE THREAD

**Issue by HumphRey123** [greenstatic/bigbluebutton-exporter#20]
Hi Gregor,

I've setup your bbb-exporter solution like your documentation .
And all services are running. But I get No Data in grafana.
Datasource is configured to http://localhost:9090 and your JSON files are imported in grafana .
Any idea?

 I've setup netdata parallel there, this works and I get data and graphs.
  
regards
Rene

**Comment by greenstatic** [comment]
Did you add bbb-exporter to your Prometheus config to allow Prometheus to scrape the metrics?
If you have, check in the Prometheus web UI under status->targets to see if it's state is _Up_.

**Comment by HumphRey123** [comment]
okay, have it....

YES, thx..., in prometheus.yml was scheme: https , for a localhost address. I've changed it to http and now it works ;-)

Thx Gregor

**Comment by greenstatic** [comment]
I assume you have prometheus on the same host as your bbb-exporter? If not, it is strongly recommended to have TLS + HTTP basic auth.

**Comment by HumphRey123** [comment]
its on the same server with http basic Auth
The BBB service himself has TLS.

**Comment by abhas** [comment]
> I assume you have prometheus on the same host as your bbb-exporter? If not, it is strongly recommended to have TLS + HTTP basic auth.

What I did with my setup is use OpenVPN to build a private network between the BBB server and the grafana/prometheus server. Then I configure node-exporter as well as bbb-exporter to listen on the VPN IP. This way I can scrape these end-points from Prometheus without any additional configuration or security issues. it also simplifies the whole setup.

**Comment by greenstatic** [comment]
@abhas that is also a possible setup with security industry best practices. But in my experience OpenVPN usually doesn't simplify setups 😛 .
