### ISSUE TITLE
Doesn't show number of rooms

### ISSUE THREAD

**Issue by dakser** [greenstatic/bigbluebutton-exporter#26]
Hi, I have installed the bbb exporter and node exporter and I have noticed that the number of rooms and participants by client type doesn't get information. Do you know if I should check something in particular to get this metrics in the dashboard working? Thanks, it's a great project.

**Comment by greenstatic** [comment]
If I understand correctly the metric for client type is completely empty when there are participants in various rooms? Anything special in the logs?

**Comment by dakser** [comment]
Hi, that's right, the metric for "client type" and "number of rooms is empty", could you give me some information to find the logs? Thank you.

**Comment by greenstatic** [comment]
Which version of the exporter are you running? Make sure you are on the latest release - v0.3.0. Best to change the image field in the docker-compose.yaml file to `greenstatic/bigbluebutton-exporter:v0.3.0` and issue a `sudo docker-compose up -d`.

If you installed recently I see we forgot to update the example docker-compose file, I'll update the docs to warn users and update the label.

**Comment by dakser** [comment]
Hi, it was working with the v0.2.0 like says in the documentation, I have updated to v0.3.0 and it's working now. Thanks again for your help!
