### ISSUE TITLE
Add note about instance relabeling for grafana dashboards

### ISSUE THREAD

**Issue by robbi5** [greenstatic/bigbluebutton-exporter#3]
First, thanks for the awesome bbb-exporter 😍 

After setting it up a few minutes ago, I was a bit confused about missing cpu/bandwidth-metrics. The instance dropdown in grafana is build by using `label_values(bbb_api_up, instance)` - in my case that returned `bbbhost.example:443`.
The instance label from my netdata appeared as `bbbhost.example:19999`. In this case, the `$instance` variable in grafana contained `bbbhost.example:443` and such the corresponding netdata metrics were not found. 

Currently I've solved it by adding the [following relabel config](https://stackoverflow.com/a/58672694) to my scrape_configs in prometheus.yml:
```
relabel_configs:
- source_labels: ['__address__']
  separator:     ':'
  regex:         '(.*):.*'
  target_label:  'instance'
  replacement:   '$1'
```

Just FYI - if you like, just close the issue - or add a note about the requirement of equal instance labels for netdata and the exporter for the dashboards :)

**Comment by greenstatic** [comment]
Thank you @robbi5 for your findings. Yeah, I made the assumption that both the exporter and Netdata will be behind the BigBlueButton Nginx reverse proxy. I will expand the documentation to include this. Thanks!
