### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by GremL1N** [greenstatic/bigbluebutton-exporter#30]
On site https://bigbluebutton-exporter.greenstatic.dev/ some typos.

- In section install `node_exporter` and `netdata` missing steps 4,5
- Also where missing auth params in nginx config or need to remove step 3 about .htpasswd
- On `node_exporter` nginx config copied from `netdata` and has commnet `#Netdata monitoring`

**Comment by greenstatic** [comment]
Thanks for your report, appreciate it. Feel free to open more issues if you find any more inconsistencies.
