### ISSUE TITLE
Scalelite support

### ISSUE THREAD

**Issue by alfredonodo** [greenstatic/bigbluebutton-exporter#31]
Hi,
does bigbluebutton-exporter support multiple BBB instances through [scalelite](https://github.com/blindsidenetworks/scalelite)?

**Comment by greenstatic** [comment]
I have not installed nor configured scalelite yet, but as far as I understand you still can query the API of each BBB instance. Meaning that from the point of view of bbb-exporter there is nothing blocking it from working. Obviously you will still need to install the exporter on each BBB instance.

Other people have setup the exporter with scalelite, as far as I know without any issues.
Example: https://github.com/greenstatic/bigbluebutton-exporter/issues/12#issuecomment-627819586

If you run into any troubles or if everything worked out of the box do report back so we can update the documentation.

**Comment by penguennoktanet** [comment]
> Other people have setup the exporter with scalelite, as far as I know without any issues.

Yep, that's me... But I did not use bbb-exporter via scalelite. I installed bbb-exporter on each BBB server itself. Because, scalelite's BBB API does not provide server based information (you can see status via rake status, not via BBB API).

**Comment by rexon07** [comment]
Hi,
I have a scalelite and 3bbb servers in the pool. I want to setup monitoring tool on the scalelite server to monitor all BBB's.
i have installed bbb-exporter on each bbb instance. 
And installed bbb-monitoring tool on scalelite server through :  https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/
But iam unable to fetch the details under grafana dashboard.
looking for help.
