### ISSUE TITLE
Add network traffic metrics

### ISSUE THREAD

**Issue by ratondeau** [greenstatic/bigbluebutton-exporter#33]
As the node_exporter seems to support statistics of the network interface and especially when there are a lot of video participants it woulld be a nice feature to see the bandwidth usage. 

I am qiute new to bbb-exporter / node exporter prometheus etc. but it seems that bbb-exporter uses node exporters metricx and adds additional bbb info to it, so it should#t not be too hard to implement.

**Comment by greenstatic** [comment]
Correct, `node_exporter` (or netdata) exports network data and the bbb dashboard uses it to display CPU vs. participants and network vs. participants graphs. This is already supported, here is a screenshot:

<img width="1322" alt="Screen Shot 2020-06-11 at 11 10 38 AM" src="https://user-images.githubusercontent.com/14580434/84367216-30e5bb80-abd4-11ea-89be-a64a61e5ee38.png">

**Comment by ratondeau** [comment]
Thanks, that's in the detail view must have slipped through.

**Comment by ratondeau** [comment]
Thanks, that's in the detail view must have slipped through.

**Comment by greenstatic** [comment]
The bandwidth stats (receive/transmit) are gathered from either node_exporter or netdata - whichever you choose to install. There are instructions on the documentation website for both: [node_exporter](https://bigbluebutton-exporter.greenstatic.dev/installation/node_exporter/) and [netdata](https://bigbluebutton-exporter.greenstatic.dev/installation/netdata/).

**Comment by greenstatic** [comment]
Did you manage to configure your Grafana dashboard correctly? If so, feel free to close the issue.

**Comment by ratondeau** [comment]
Weird thing is that I do see the bandwidth for my bbb3 server, but not for 1 and 2 although I did exactly the same steps. What could be the cause for that?

**Comment by greenstatic** [comment]
Try to see if Prometheus is scraping the metrics correctly, follow the [Checking if Prometheus is Scraping Correctly](https://bigbluebutton-exporter.greenstatic.dev/debugging/#checking-if-prometheus-is-scraping-correctly) instructions but instead of `bbb_node_exporter` check your `node_exporter` / `netdata` scrape job.

**Comment by ratondeau** [comment]
I had a look everything is up and running and I see the proper information there, so I guess it is somehow Grafana/Prometheus related.  This is my job config:

`- job_name: 'bbb-node-exporter'
    metrics_path: '/node_exporter/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    scheme: https
    basic_auth:
      username: "monitoring"
      password: "password"
    static_configs:
    - targets: ['bbb1', 'bbb2', 'bbb3']
`

I will close this issue then.
