### ISSUE TITLE
Error when running nginx

### ISSUE THREAD

**Issue by eyerefin** [greenstatic/bigbluebutton-exporter#35]
When installing I am having error running nginx. 

When testing with `sudo nginx -t` it is showing

```
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/bigbluebutton:85
nginx: configuration file /etc/nginx/nginx.conf test failed
```

the config that is giving me the error,

```
# BigBlueButton Exporter (metrics)
location /metrics/ {
    auth_basic "BigBlueButton Exporter";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://127.0.0.1:9688/;
    include proxy_params;

}
```

**Comment by greenstatic** [comment]
Are you sure you are placing the location config in the right block in the bigbluebutton nginx config? I have a feeling that you did not place the location config into the `server` block.

**Comment by eyerefin** [comment]
I am placing the config in the very last of the file. 
Can you please guide me where I need to place the config code?

**Comment by greenstatic** [comment]
Above or bellow the existing location directives, so within the `server` block.
So something like this:

```
server {
  location ....

  location ....
}
```

**Comment by greenstatic** [comment]
Did you manage to make it work? If so, feel free to close the issue.

**Comment by greenstatic** [comment]
Closing this for now, feel free to reopen the issue if you have any more trouble regarding this.
