### ISSUE TITLE
Import custom CA for a self-signed cert into bbb-exporter container

### ISSUE THREAD

**Issue by nine1zero** [greenstatic/bigbluebutton-exporter#39]
Would like to add a custom CA for a self-signed SSL certificate installed on BBB instance.

The log from bbb-exporter says:
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

I did the All-In-One Monitoring Stack but I can't really find where is the dockerfile for the bbb-exporter service to add something like (or how is pulled from git if just the .yaml is provided):

-- Dockerfile
FROM some-base-image:0.1
ADD my_certificate.crt:/container/cert/path
RUN update-ca-certificates 

many thanks

**Comment by greenstatic** [comment]
If I understand correctly your BigBlueButton does not have a valid TLS certificate? Considering BBB is meant for end users having a non-valid TLS certificate is not the best idea. In case you are not aware you can get a free signed TLS certificate from [Let's Encrypt](https://letsencrypt.org/). The only other reason I see for not having a valid certificate is if your organization has their own CA or your are just testing things out in a lab environment.

Otherwise you are correct that we currently do not support disabling CA cert verification or adding your own CA. But we can add that functionality no problem. I could maybe squeeze this and have a preview build within 24 hours. Would you be willing to test our the preview build before we make it into a release?

**Comment by greenstatic** [comment]
Just implemented this feature (#40) and built a preview build ([greenstatic/bigbluebutton-exporter:v0.4.1-preview1](https://hub.docker.com/layers/greenstatic/bigbluebutton-exporter/v0.4.1-preview1/images/sha256-9dc98d0b174102dc5d6271df0214f41e58c8baf4c76ec5d4db397aaa59d8c070?context=explore)) for tesitng.
You can either build the image yourself from the PR or use the preview build linked above.

## Recommended
You mentioned you are using the all-in-one monitoring stack, here are the instructions on how to test the preview build:
1. Open the all-in-one monitoring stack `docker-compose.yaml`
2. Replace the `services.bbb-exporter` section with the following snippet. Be **careful** to have your spaces aligned properly, use the remaining services as a template for the correct number of spaces for alignment.
```yaml
  bbb-exporter:
    container_name: bbb-exporter
    image: greenstatic/bigbluebutton-exporter:v0.4.1-preview1
    network_mode: host
    env_file:
      - bbb_exporter_secrets.env
    environment:
      TLS_VERIFY: "/app/CA_BUNDLE.txt"
    volumes:
      - "./CA_BUNDLE.txt:/app/CA_BUNDLE.txt"
    restart: unless-stopped
```
3. Where your `docker-compose.yaml` file is located create a `CA_BUNDLE.txt` file and populate it with your self-signed root CA certificate and any intermediate CA certificates you wish to add.
4. Run `sudo docker-compose up -d` to start the all-in-one monitoring stack. Check the logs (`sudo docker-compose logs bbb-exporter --follow`) for the line `Using custom TLS CA_BUNDLE path (<PATH>) for API call` - if you see it and there are no other errors in the logs it means everything was successful.

## Not Recommended
In case you wish to disable the TLS CA verification you can copy the above snippet and set `TLS_VERIFY: "false"` and remove the `volumes` section. This will completely disable the TLS certificate verification and your connection will be vulnerable to man in the middle attacks, use this ONLY if you are testing things out in a lab environment.

If you experience any bugs or issues please report them here, also if everything works as expected report back so we can merge this into master and create a new release.

**Comment by nine1zero** [comment]
Exactly! Are the option 2 and 3 combined, is a large organisation with their own custom CA and actually is a lab environment at the moment. Moreover the “monitoring stack” is on the same host of BBB, so not really big trust issue for the api calls. At the moment I had to disable the cert verification manually editing the python code but would be more than glad to test out an enhancement for adding a custom CA.

Many thanks for lighting support and your work.

**Comment by greenstatic** [comment]
Did you get a chance to test out the preview build?

**Comment by nine1zero** [comment]
Yes @greenstatic the TLS_VERIFY works with no problems:

bbb-exporter     | 2020-07-13 09:38:51,030 [INFO]: TLS CA verification has been disabled for API call
bbb-exporter     | /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mysite.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

but with the validation gives me:

bbb-exporter     | 2020-07-13 09:54:35,727 [INFO]: Using custom TLS CA_BUNDLE path (/app/CA_BUNDLE.txt) for API call
bbb-exporter     | 2020-07-13 09:54:35,733 [ERROR]: Failed to perform API call
bbb-exporter     | 2020-07-13 09:54:35,733 [ERROR]: HTTPSConnectionPool(host='mysite.com', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=9df7de9d411a46f6d9c64e71ec78b280436ac675&state=deleted (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:4109)')))
bbb-exporter     | 2020-07-13 09:54:35,738 [INFO]: Finished collecting metrics from BigBlueButton API

in the CA_BUNDLE.txt I have (rename to .prm from .crt), does order matters?

/usr/local/share/ca-certificates/SubCA.pem
/usr/local/share/ca-certificates/Root.pem

in the volumes in docker-compose.yaml I have to add the directory with .pem as well:

    volumes:
      - "./CA_BUNDLE.txt:/app/CA_BUNDLE.txt"
      - "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates"

Doing something wrong? I think the certificate dir pointed in the .txt should be mounted right?

**Comment by greenstatic** [comment]
If you are going to use a custom CA_BUNDLE you do not need the `- "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates"` line, since the bbb-exporter container _should_ only perform external requests to the BBB server from the bigbluebutton-exporter process and no other network requests.

You are probably doing the CA_BUNDLE wrong as well. You can either specify a directory then set `TLS_VERIFY` to the directory path OR (like you did) set `TLS_VERIFY` to a file path which contains an appended list of all the certificates (root and subca).

If you are going with the "file" flavor, your file should look something like this:
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

If that still doesn't work, check that your BBB certificate is actually signed by the root CA/sub CA that you are using in the CA_BUNDLE.

**Comment by nine1zero** [comment]
thanks, after your instructions, working perfectly now. I think can be merged to master the PR (maybe would be useful to specify to append every custom certificate chain in the CA_BUNDLE.txt file and not the full path of them (was my error).
Thanks again for the support

**Comment by greenstatic** [comment]
Will merge this this evening, create a release and update the docs. Thanks for the feedback!

**Comment by greenstatic** [comment]
Just an FYI, I just made a release: [v0.5.0](https://github.com/greenstatic/bigbluebutton-exporter/releases/tag/v0.5.0). I recommend you change the docker image tag to be on a stable build :)

**Comment by linuxmangr** [comment]
> thanks, after your instructions, working perfectly now. I think can be merged to master the PR (maybe would be useful to specify to append every custom certificates in the CA_BUNDLE.txt file and not the full path of them (was my error). Thanks again for the support

Hi,
Can you write all steps what you do to resolve the problem
Thank you!
