### ISSUE TITLE
[BBB2.3Alpha1] bbb-exporter not binding to port 9688

### ISSUE THREAD

**Issue by bayden10** [greenstatic/bigbluebutton-exporter#42]
I have several BBB hosts on v2.2.19 running bbb-exporter & node_exporter which I have no issues, but when running on Ubuntu 18.04 and BBB2.3A1 the bbb-export does not bind to port 9688 so no connection to Prometheus. 

```
 netstat -a -n -p|grep exporter
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      2676/node_exporter
```
```
 netstat -a -n -p|grep :9688
~/bbb-exporter#
```

```
bbb-conf --check

BigBlueButton Server 2.3.0-dev (1183)
                    Kernel version: 4.15.0-109-generic
                      Distribution: Ubuntu 18.04.4 LTS (64-bit)
                            Memory: 32143 MB
                         CPU cores: 8
```
and after dock-compose down / up status stuck at restarting

```
docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED              STATUS                          PORTS                      NAMES
3ab73361a352        greenstatic/bigbluebutton-exporter:v0.4.0   "python server.py"       About a minute ago   Restarting (1) 19 seconds ago                              bbb-exporter
c75776abdf56        prom/node-exporter:v0.18.1                  "/bin/node_exporter …"   23 hours ago         Up 17 hours                                                node_exporter
95a0eff3d736        bbb23a-12:release-v2.6.5                    "bin/start"              47 hours ago         Up 17 hours                     127.0.0.1:5000->80/tcp     greenlight-v2
9fd2eb70a6bf        postgres:9.5                                "docker-entrypoint.s…"   47 hours ago         Up 17 hours                     127.0.0.1:5432->5432/tcp   greenlight_db_1
```

**Comment by greenstatic** [comment]
What do the logs for bbb-exporter say?
```shell
sudo docker logs bbb-exporter
```

**Comment by bayden10** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/bigbluebutton/recording/status/published'
```

**Comment by greenstatic** [comment]
You probably have [RECORDINGS_METRICS_READ_FROM_DISK](https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations) enabled and forgot to bind mount the mentioned dir into the bbb-exporter container.

**Comment by bayden10** [comment]
Set to false now and image is running but still not able to browse /metrics nor Prometheus connects to bbb-exporter.

```
docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                      NAMES
02ac6f11f3a1        greenstatic/bigbluebutton-exporter:v0.4.0   "python server.py"       3 minutes ago       Up 3 minutes        127.0.0.1:9688->9688/tcp   bbb-exporter
```

**Comment by greenstatic** [comment]
Have you [setup Nginx on your BBB server](https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#6-add-nginx-site-configuration) to act as a reverse proxy for the /metrics endpoint?

The following command will locally (on your machine) forward the port 9688 to the BBB server 127.0.0.1:9688 bind:
```
ssh -NL 9688:127.0.0.1:9688 <BBB HOST>
```
Then visit `http://localhost:9688` locally - on your machine. If you see metrics then the BBB exporter is working without any issues and you have a reverse proxy Nginx issue.

**Comment by bayden10** [comment]
Yes you are correct, I had reverse proxy using another port for exporter while troubleshooting and forgot to return to default, made the update to use 9688 and all is working now.

Thank you for your help.

**Comment by greenstatic** [comment]
No problem, feel free to close the issue.
