### ISSUE TITLE
No hardware-metrics in All-In-One-Monitoring Stack

### ISSUE THREAD

**Issue by Dimitrie23** [greenstatic/bigbluebutton-exporter#43]
Hi! I'm trying to get the monitoring working with this excellent project. But I can't get it to display me the network/cpu/memory, etc. All I see in my grafana dashboard is the bbb-exporter with participants and the metrics response times/api. Checking the output of the Prometheus metrics like suggested in https://bigbluebutton-exporter.greenstatic.dev/debugging/. I can see the values and that the node_exporter is working and scraping correctly. My BBB-Instance is set up by the install-script on a root-server, so nothing is changed there. So guessing from the debugging section the problem lies between grafana and prometheus. since all targets are up. But i don't understand what is wrong there. The data source is set to Prometheus with http://localhost:9090 and delivers data (if you ask grafana) but it is only the bbb-exporter-data. Did I miss anything crucial during the setup?

**Comment by Dimitrie23** [comment]
Found it. It's an issue with the link in the setup guide: https://github.com/greenstatic/bigbluebutton-exporter/blob/master/extras/dashboards/server_instance_netdata.json but it should be the node_exporter-version: https://github.com/greenstatic/bigbluebutton-exporter/blob/master/extras/dashboards/server_instance_node_exporter.json
now everthing works. But you might want to correct that in the guide.

**Comment by greenstatic** [comment]
You're right, the wrong link is in the docs. Thanks for the warning, fill fix.
