### ISSUE TITLE
Empty charts

### ISSUE THREAD

**Issue by ehsanrasta** [greenstatic/bigbluebutton-exporter#46]
Hi
I have a problem with "all in one monitoring" that shows no data in charts.
It works randomly and after reboot sometimes this error happening:

> bbb-exporter     | Exception happened during processing of request from ('127.0.0.1', 36600)
> bbb-exporter     | Traceback (most recent call last):
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
> bbb-exporter     |     self.finish_request(request, client_address)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
> bbb-exporter     |     self.RequestHandlerClass(request, client_address, self)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
> bbb-exporter     |     self.handle()
> bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
> bbb-exporter     |     self.handle_one_request()
> bbb-exporter     |   File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
> bbb-exporter     |     method()
> bbb-exporter     |   File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET
> bbb-exporter     |     self.wfile.write(output)
> bbb-exporter     |   File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
> bbb-exporter     |     self._sock.sendall(b)
> bbb-exporter     | BrokenPipeError: [Errno 32] Broken pipe

![Untitled](https://user-images.githubusercontent.com/35690824/88458550-20e41b80-cea4-11ea-90f0-4864ec9c1286.png)

**Comment by greenstatic** [comment]
This sounds like the same issue as: https://github.com/greenstatic/bigbluebutton-exporter/issues/29#issuecomment-656214404

Try the solution I posted there: https://github.com/greenstatic/bigbluebutton-exporter/issues/29#issuecomment-658591700

I still haven't managed to update the docs like I said I will, will do that tonight. 

Hope it helps.

**Comment by ehsanrasta** [comment]
Thank you 

Added RECORDINGS_METRICS_READ_FROM_DISK to docker-composer.yaml and fixed the problem
