### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by amg-web** [greenstatic/bigbluebutton-exporter#47]
The better way  to place nginx config for exporter is 
**/etc/bigbluebutton/nginx/metrics.nginx**

it will not be overwritten during update

**Comment by greenstatic** [comment]
I agree it is better practice to separate the Nginx site configuration to prevent it from being overwritten during BBB upgrading. This is also [mentioned in the docs](https://github.com/greenstatic/bigbluebutton-exporter/blob/2ec4748e37e7e22f85c09a9a7ef00c1b554dfa5e/docs/installation/bigbluebutton_exporter.md#6-add-nginx-site-configuration), however it requires for a separate HTTPS certificate.

**Comment by amg-web** [comment]
if you open /etc/nginx/sites-available/bigbluebutton
you will find this line
 include /etc/bigbluebutton/nginx/*.nginx;

that's why I mentioned it in previous message

**Comment by greenstatic** [comment]
Hmm I never noticed that. That's an interesting idea! One thing personally though is that I sort of expect all Nginx configs to be in `/etc/nginx/sites-available`. I think it would hurt readability a bit, but on the second hand I suppose bbb leaves the directory alone during an upgrade? Do you have any experience regarding that?

**Comment by amg-web** [comment]
sure. no problem.
Greenlight drops its' config there

**Comment by greenstatic** [comment]
That's good news. I think I'll fix the documentation to reflect your recommendation. Thanks!

You are also welcome to submit a PR :)

**Comment by amg-web** [comment]
`You are also welcome to submit a PR :)`
What do you mean PR ?

**Comment by greenstatic** [comment]
PR = [Pull request](https://guides.github.com/activities/hello-world/#pr)

**Comment by amg-web** [comment]
I made it :)

**Comment by greenstatic** [comment]
Great, thanks!

Merged in #59
