### ISSUE TITLE
Yaml scanner error Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ChrisPyJ** [greenstatic/bigbluebutton-exporter#50]
root@myvacademy-production-server:~/bbb-monitoring# docker-compose up -d
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yaml", line 123, column 34
root@myvacademy-production-server:~/bbb-monitoring# docker-compose -v
docker-compose version 1.24.0, build 0aa59064
root@myvacademy-production-server:~/bbb-monitoring#

**Comment by greenstatic** [comment]
Next time to avoid formatting issues when pasting program outputs use [code blocks](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

Are you sure you copied the contents correctly, [docker-compose.yaml](https://github.com/greenstatic/bigbluebutton-exporter/blob/2ec4748e37e7e22f85c09a9a7ef00c1b554dfa5e/extras/all_in_one_monitoring/docker-compose.yaml) file for the all in one monitoring stack doesn't have 123 lines.

**Comment by ChrisPyJ** [comment]
That was clue. Imported via wget that caused this error. Now its perfectly running

**Comment by greenstatic** [comment]
Great to hear, feel free to close the issue.
