### ISSUE TITLE
Monitoring CPU usage in GHz using Prometheus node_exporter

### ISSUE THREAD

**Issue by voicerecordist** [greenstatic/bigbluebutton-exporter#54]
I simply monitor CPU usage in percentage format, but I don't know how to monitor CPU in gigahertz format. any ideas?

**Comment by greenstatic** [comment]
You should checkout what node_exporter (or if you're using netdata) exports. This might help: https://www.robustperception.io/cpu-frequency-scaling-metrics-from-the-node-exporter.

**Comment by greenstatic** [comment]
Closing this for now. Feel free to reopen the issue if you have any additional questions regarding this.
