### ISSUE TITLE
[Help] - Only netdata dashboard data collection

### ISSUE THREAD

**Issue by GhaziTriki** [greenstatic/bigbluebutton-exporter#56]
Hi @greenstatic 
Can I only use the netdata dashboard display for this exporter?

**Comment by greenstatic** [comment]
You can either use netdata OR node_exporter for the system metrics. You just need to import the correct dashboard. see the links mentioned under "Instalaltion type matrix" https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installation-type-matrix

**Comment by greenstatic** [comment]
Have you managed to find a solution?

**Comment by greenstatic** [comment]
Closing this for now. Feel free to reopen the issue if you have any additional questions regarding this.
