### ISSUE TITLE
Error starting the service

### ISSUE THREAD

**Issue by 2860166** [greenstatic/bigbluebutton-exporter#58]
Hi. wen i run `sudo docker-compose up -d`, i got the error:
`ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
`

**Comment by greenstatic** [comment]
How did you install docker? The default Docker package in Ubuntu repositories (assuming you have Ubuntu) are quite old. It's best to follow Docker's installation guide (by adding their APT repo).

**Comment by 2860166** [comment]
I am using ubuntu. I've installed it by `sudo apt install`

**Comment by greenstatic** [comment]
See https://github.com/greenstatic/bigbluebutton-exporter/issues/21

The docs mention this for the all in one monitoring stack, but it's valid for other docker-compose related installations as well. Will move the warning in the docs to a more more general section.
