### ISSUE TITLE
"No Data" in Grafana when under load

### ISSUE THREAD

**Issue by jhartleycaw** [greenstatic/bigbluebutton-exporter#61]
Hi,

We are finding that when load ramps up on our server(dual Xeons, 48GB RAM), ie around 100 students, BBB-exporter stop working, then at lunchtimes or end of day when people leave, we get reporting again. We can access Grafana, just get the No Data in all boxes.

It does not seem to affect any of the working of BBB itself. We are not taxing our server at all, we regularly have 250 students over multiple rooms. We purposefully overspecced the bare metal for this project just in case.

We since updated to 0.5.2 from an 0.4 version to try and sort this, now the dashboard randomly goes between No Data and reporting, not just under load.

Do you any insight into this?

Thanks
James

**Comment by greenstatic** [comment]
The "No Data" is displayed in all boxes or just some - in which dashboard specifically? A couple of panels in the dashboard (e.g. exporter version) only query the latest metric while other like the participants panel query a range of values.

If this "No Data" issue is confined to only the panels configured with latest metric then there indeed is an issue with scraping bbb metrics.

I have not seen this issue before. Where is your Prometheus instance located - on the same server? Another possible issue is the network connectivity between the Prometheus instance the the BBB server - if Prometheus can't scrape the values, Grafana can't dislpay them.

**Comment by jhartleycaw** [comment]
It is in all boxes, and occasionally flicks on and starts working, showing the Exporter version and metrics, but seems random. Everything is on the same server, following the all in one monitoring stack instructions in the BBB docs

**Comment by greenstatic** [comment]
So "No data" is also shown for the participants panel?

**Comment by greenstatic** [comment]
Does the participants panel and/or the other panels like CPU, memory, etc. have missing metrics?

**Comment by jhartleycaw** [comment]
At the moment, I have no metrics at all, every panel and graph is no data. I have force recreated the docker images, and made sure the compose is up, and nothing. I have checked the secrets in the ENV file, and made sure the directive is still in nginx

**Comment by greenstatic** [comment]
This sounds more like a Grafana -> Prometheus networking issue. I'm stumped why it works sometimes.

Try [connecting to your Prometheus instance](https://bigbluebutton-exporter.greenstatic.dev/debugging/#checking-if-prometheus-is-scraping-correctly) and seeing if the metrics are being scraped normally.

**Comment by jhartleycaw** [comment]
Just checked the logs first:
bbb-exporter     | Exception happened during processing of request from ('127.0.0.1', 53558)
bbb-exporter     | Traceback (most recent call last):
bbb-exporter     |   File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
bbb-exporter     |     self.finish_request(request, client_address)
bbb-exporter     |   File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
bbb-exporter     |     self.RequestHandlerClass(request, client_address, self)
bbb-exporter     |   File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
bbb-exporter     |     self.handle()
bbb-exporter     |   File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
bbb-exporter     |     self.handle_one_request()
bbb-exporter     |   File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
bbb-exporter     |     method()
bbb-exporter     |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 159, in do_GET
bbb-exporter     |     self.wfile.write(output)
bbb-exporter     |   File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
bbb-exporter     |     self._sock.sendall(b)
bbb-exporter     | BrokenPipeError: [Errno 32] Broken pipe
bbb-exporter     | ----------------------------------------
bbb-exporter     | 2020-10-01 07:54:49,255 [INFO]: Collecting metrics from BigBlueButton API
bbb-exporter     | 2020-10-01 07:54:51,506 [INFO]: Finished collecting metrics from BigBlueButton API


Could it be a python error then? Does it use the local version of python or the docker internal version?

Thanks
James

**Comment by greenstatic** [comment]
If you are running the all in one monitoring stack, the bbb exporter Docker container has it's own Python that is compatible.

This seems to me like a timeout issue, do you have the recordings metrics over disk optimization enabled? Prometheus queries the exporter and the exporter takes too long to respond. This is usually because when bbb exporter queries bbb (via it's XML api), the calls for getting the number of recordings take a long time (multiple seconds and upwards to a minute) when you have many recordings. This is because the only way for bbb exporter to get the number of recordings is to get all the recordings which returns a giant response (upwards from a MB). Recent versions of the exporter come with an optimization that reduces this to under a second because it queries this information directly on the disk instead of via bbb's API. You can read more about it here: https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations

Check the newest release of the all in one monitoring stack yaml files (docker-compose and the .env files) how to enable this optimization.

**Comment by jhartleycaw** [comment]
I think that might have done it! Turned on the optimization in the env, and created a read only mount to the bbb-exporter. So basically, as our amount of recording went up at the start of the college year, it got harder to query all the recordings, hence the timeouts? We currently have 500 recordings

**Comment by greenstatic** [comment]
Yeah with 500 recordings it definitely is an issue, I remember in our case with 100+ recordings it took sometimes 10 seconds. The default Prometheus scrape timeouts probably kicked in :). Glad it seems to be working. Feel free to close the issue.

**Comment by jhartleycaw** [comment]
Thanks again, much appreciated, will close now.

James
