### ISSUE TITLE
take long time (5-15 sec) to show /metrics

### ISSUE THREAD

**Issue by cod3r0k** [greenstatic/bigbluebutton-exporter#62]
Dear all, I have a problem in one server which related to the `/metrics/` route.
How can I found that why it takes a long time to generate?

**Comment by greenstatic** [comment]
Do you have the reading recordings metrics from disk optimization enabled? https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations

**Comment by cod3r0k** [comment]
Thanks. it was resolved. @greenstatic
