### ISSUE TITLE
smtp setings grafana (docker)

### ISSUE THREAD

**Issue by chezmohamed** [greenstatic/bigbluebutton-exporter#64]
Hi!
i spent nights looking for how to configure grevana to send email alerts, i didn't succeed.
I found some solution, enter the grefana bash
docker-compose exec grafana bash
and change the configuration file:

 vi conf / default.ini

but when I want to exit by esc -: w that does not quit
can someone help me?

**Comment by greenstatic** [comment]
What you are doing is not going to work. You are spawning a shell into the container, making changes and not even restarting Grafana to apply the changes. If you would restart Grafana in the container you would probably see the configuration changes. But don't be fooled! You are working with containers. If (when) the container will get deleted and a new one is created, none of your changes will be there.

I assume you are using the all in one monitoring solution. You simply need to override the environment variables of the container's configuration in the `docker-compose.yaml` file, right about here: https://github.com/greenstatic/bigbluebutton-exporter/blob/f8c589f6350d4c3b06dafce120f61f674d634b6a/extras/all_in_one_monitoring/docker-compose.yaml#L40-L43.

See Grafana's documentation for the proper configuration with environment variables: https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables

Once you have your new configuration environment variables, simply run `sudo docker-compose up -d` and it will recreate the container (therefore deleting your `default.ini` changes) with the new environment variables.

**Comment by chezmohamed** [comment]
A very big thank you you saved my life

**Comment by greenstatic** [comment]
If your life depends on Docker and containers in general I suggest you review these resources:
* https://www.katacoda.com/courses/docker/
* https://qconsf2017intro.container.training/

Otherwise you're welcome :)

**Comment by chezmohamed** [comment]
Thank you for your generosity :)
