### ISSUE TITLE
How can we pass service status 

### ISSUE THREAD

**Issue by cod3r0k** [greenstatic/bigbluebutton-exporter#66]
Dear all, I want to check service status (mongod,bbb-html5,...) in grafana. How can we pass services status with bbb-exporter? @greenstatic @faust64 @pkoro

**Comment by greenstatic** [comment]
For mongo there are exporters available:
* https://github.com/dcu/mongodb_exporter
* https://github.com/percona/mongodb_exporter

Simply follow their installation guides and configure your Grafana dashboard to query the metrics (or if the exporters provide dashboards, use them).

For bbb-html5 I'm not sure. What kind of metrics would you like?

**Comment by cod3r0k** [comment]
> For mongo there are exporters available:
> 
> * https://github.com/dcu/mongodb_exporter
> * https://github.com/percona/mongodb_exporter
> 
> Simply follow their installation guides and configure your Grafana dashboard to query the metrics (or if the exporters provide dashboards, use them).
> 
> For bbb-html5 I'm not sure. What kind of metrics would you like?

Dear @greenstatic , Thanks. No, I want to check some important services as you can see in the below image
![image](https://user-images.githubusercontent.com/36899025/96719268-0a236700-13b6-11eb-8d52-99098b9ea92f.png)


The image is generated with installation of https://grafana.com/grafana/dashboards/8348.

But I didn't want to install another thing in BBB servers and I want to know that, is there any solution in BBB-exporter or node_exporter or etc to handle these requirements? 

I just want to know that each service of each servers is ON and not being faild.

**Comment by greenstatic** [comment]
I don't think there is anything from the BBB API that can hint at a mongodb failure or bbb-html5. You might be better off searching for a docker container exporter (similar to the systemd exporter you linked earlier).

**Comment by cod3r0k** [comment]
> I don't think there is anything from the BBB API that can hint at a mongodb failure or bbb-html5 - which would be required to incorporate into bigbluebutton-exporter. You might be better off searching for a docker container exporter (similar to the systemd exporter you linked earlier).

Thanks. Node exporter (https://github.com/prometheus/node_exporter) said that it can pass OS services. Is it different from bigbluebutton-exporter (which had a node_exporter section)?

**Comment by greenstatic** [comment]
The node_exporter section is just a guide how to install Prometheus' node_exporter on a bbb server. So in a container and behind nginx. Nothing special about it. 

I don't know how node_exporter's OS services works exactly in a containerized environment. You might have some issues there.

**Comment by cod3r0k** [comment]
> The node_exporter section is just a guide how to install Prometheus' node_exporter on a bbb server. So in a container and behind nginx. Nothing special about it.
> 
> I don't know how node_exporter's OS services works exactly in a containerized environment. You might have some issues there.

Wow, You said a good intuition! which we I think we must install another ones to focus on OS services.
Thanks for your answering.

So, I think I must use https://grafana.com/grafana/dashboards/8348 (Getting status of SystemD services using Telegraf+InfluxDB+Grafana). Don't you have any further suggestion?

**Comment by greenstatic** [comment]
Don't know. Report back with your findings :)

**Comment by faust64** [comment]
Sorry for the late reply. To complete greenstatic answer,

- as already suggested: https://github.com/percona/mongodb_exporter for mongodb. The dcu one is pretty old, missing metrics, ... while the percona one is based on the other, .. should be the way to go.
- https://github.com/nginxinc/nginx-prometheus-exporter/ for nginx
- https://github.com/oliver006/redis_exporter for redis
- https://pypi.org/project/prometheus-freeswitch-exporter/ for freeswitch

Also, running Scalelite and/or Greenlight, we could use:

- https://github.com/wrouesnel/postgres_exporter/ for postgres
- https://github.com/prometheus/blackbox_exporter/ (basic http checks against nginx / vhosts availability)

For what it's worth, I've just published the playbooks I'm working on: https://github.com/Worteks/bbb-ansible
Deploying BBB,  Scalelite, Greenlight, with  Prometheus/Grafana and proper dashboards.
