### ISSUE TITLE
Cannot run docker-compose - Cannot start service prometheus

### ISSUE THREAD

**Issue by musyne** [greenstatic/bigbluebutton-exporter#72]
My install is standard BBB 2.2.0 on recommended Ubuntu. Recently upgraded to latest 2.2 using bbb-install.sh.

The error I get is:
ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/bbb-monitoring/prometheus.yaml\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/6b9208ebd3b177f00442f141c1d762f2dbde7c47f3f78f5b3fbc5f9c4e7231d8/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/6b9208ebd3b177f00442f141c1d762f2dbde7c47f3f78f5b3fbc5f9c4e7231d8/rootfs/etc/prometheus/prometheus.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by greenstatic** [comment]
Are you sure you copied the docker-compose file correctly? I assume you are running the All in One Monitoring Stack installation. What seems fishy to me is this line in your error `/root/bbb-monitoring/prometheus.yaml\`; note the last slash, for some reason it believes prometheus.yaml is a directory. Have you copied the `prometheus.yaml` file?

**Comment by musyne** [comment]
Hmm. it seems when I saved the file from GitHub using Edge it renamed to prometheus.yml instead of prometheus.yaml.
It doesn't do that with Safari.
So my bad, it's probably just a filename issue that I didn't catch. I'll try to continue the setup later.
Thanks a lot.

**Comment by greenstatic** [comment]
Glad you solved your issue. Feel free to close the issue.
