### ISSUE TITLE
Dashboard not connecting first, has to switch datasource to make it work

### ISSUE THREAD

**Issue by musyne** [greenstatic/bigbluebutton-exporter#73]
Hi, small issue I guess but when I load the dashboard at first I get "NO DATA" everywhere.
The datasource is already pre-filled with "Prometheus".
If I switch to "default" then it works fine. I can switch back to "Prometheus" and it also work fine.

![Screenshot 2020-11-16 at 11 46 40](https://user-images.githubusercontent.com/10268614/99243752-66d14080-2801-11eb-93f8-25752609ee1e.png)

**Comment by greenstatic** [comment]
Does this happen every single time?

**Comment by greenstatic** [comment]
Try selecting all the correct variables, save the dashboard (don't forget to click save current variables checkbox) and try reloading.

**Comment by musyne** [comment]
Thanks. All good now.

**Comment by parrajeremy** [comment]
Same experience. 

Steps to replicate:

1. Install follow along with https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/
2. After step 6 Choose 'Default' from 'Datasource' and data populates
3. After toggle back to source 'prometheus' and data continues to be available 
4. Saving the dashboard does ensure that data is available in new sessions

**Comment by greenstatic** [comment]
Thanks for the bug report, will look into it.

**Comment by crosscodr** [comment]
Hi!
I noticed a similar problem in my custom installation: In the panel templates for jobs job_node_exporter and jobs_netdata, there are two with hard coded datasource attribute ("Prometheus"). All other entries have `"datasource": "$datasource"` set, so I switched to that in the following lines:
server_instance_netdata.json: lines 2066 and 2045
all_servers.json: lines 2570 and 2592
server_instance_node_exporter.json: lines 2053 and 2074

**Comment by greenstatic** [comment]
@crosscodr 
Yes that is probably the culprit. Would you mind making a PR with the mentioned changes?

**Comment by crosscodr** [comment]
Sure, give me a second.

**Comment by greenstatic** [comment]
Fixed by: https://github.com/greenstatic/bigbluebutton-exporter/pull/82
