### ISSUE TITLE
not getting bbb-exporter data

### ISSUE THREAD

**Issue by talfari** [greenstatic/bigbluebutton-exporter#79]
Hi,
i've 3 BBB-servers running, each with the all-in-one-monitoring stack. I know, that i could be monitoring all servers from one host, but havn't taken the time to set it up. 
I installed the first server several months ago, and don't remember every step i made but it working as expected. 
I installed 2 new servers last week and followed the instructions on the install page. The result is, that i'm getting the cpu-load network traffic and storage data shown, but no data about bbb. The BBB-API is shown as offline.

The logs of bbb-exporter shows:

bbb-exporter     | 2021-01-18 21:13:25,671 [INFO]: Collecting metrics from BigBlueButton API
bbb-exporter     | 2021-01-18 21:13:25,673 [ERROR]: Failed to perform API call
bbb-exporter     | 2021-01-18 21:13:25,673 [ERROR]: HTTPSConnectionPool(host='xxxx.xxxx.xx', port=443): Max retries exceeded with url: /bigbluebutton/api/getMeetings?checksum=e78829b66736e7b727d408fe8f6025e3e108d0a9 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fd26c9220>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
bbb-exporter     | 2021-01-18 21:13:25,675 [ERROR]: Failed to perform API call
bbb-exporter     | 2021-01-18 21:13:25,675 [ERROR]: HTTPSConnectionPool(host='xxxx.xxxx.xx', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=da104d682d9a4643739b8a807a4046bb216124a5&state=unpublished (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fd26c9220>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
bbb-exporter     | 2021-01-18 21:13:25,675 [INFO]: Path /var/bigbluebutton/recording/process/presentation doesn't exist, setting processing recordings to 0
bbb-exporter     | 2021-01-18 21:13:25,675 [INFO]: Path /var/bigbluebutton/recording/status/published doesn't exist, setting deleted recordings to 0
bbb-exporter     | 2021-01-18 21:13:25,676 [INFO]: Finished collecting metrics from BigBlueButton API

Can anybody give me a hint about what i'm missing?

Best regards and thank you

**Comment by greenstatic** [comment]
Network traffic and storage data is returned by node_exporter. What you are seeing is an error from bigbluebutton-exporter. It failed to connect to your BBB server. Double check your base_url & secret. The base_url is often: `https://bbb.example.com/bigbluebutton/api/` - the path and trailing slash is very important!

**Comment by talfari** [comment]
hte url was teh problem: Missed the trailing /api/ on one server AND had a typo on the other. Therfor I din't see any difference on adding api or not.
Thank you!!!!
