### ISSUE TITLE
All metrics there but Dashboard shows everywhere "No data"

### ISSUE THREAD

**Issue by jacotec** [greenstatic/bigbluebutton-exporter#84]
I've installed the all-in-one-monitoring via docker on my BBB-Server following the really excellent documentation here: https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/

Unfortunately after importing the Dashboard JSON, all data points in the dashboard are showing "No Data":

![grafik](https://user-images.githubusercontent.com/3321655/108089055-7880e900-7079-11eb-95db-7f2e812b7166.png)

In the data explorer I see that the data sources and data points from Prometheus and node are all fine with matching data:

![grafik](https://user-images.githubusercontent.com/3321655/108089366-cdbcfa80-7079-11eb-99cc-2550bf84de5d.png)

Any idea what can be wrong with the dashboard? I've deleted it and reimported the "server_instance_node_exporter.json " again, but still no change.

**Comment by greenstatic** [comment]
You don't have a job / job node_exporter selected in the top left corner of Grafana.

**Comment by jacotec** [comment]
@greenstatic Thank you for this hint! The selection is a bit tricky - opening the dropdown and select "bbb" does not help, you need to open the dropdown and click somewhere into the empty space below the "bbb" selection.

![grafik](https://user-images.githubusercontent.com/3321655/108120750-0f619b80-70a2-11eb-88e3-c97e9a0b869b.png)

Is there a way to save that into the dashboard file? When I close the monitoring and reopen it, it's back to "No data" and I need to reselect the job every time (by clicking into the nowehereland below).

**Comment by greenstatic** [comment]
1. Select all the correct variables
2. Top right corner click the save dashboard icon, in the dialog there will be a checkbox for "save variables as default" something along those lines.
3. Click the save button

**Comment by jacotec** [comment]
Awesome, that's what I was looking for! Thank you for that great project!

PS: Might be worth mentioning that job issue in the docs ;-)

**Comment by greenstatic** [comment]
Thanks for the kind words.

I would gladly accept a PR :).
