### ISSUE TITLE
Storage Utilization with All-In-One Stack

### ISSUE THREAD

**Issue by LiohMoeller** [greenstatic/bigbluebutton-exporter#87]
I am using the All-In-One Stack and everything works as expected besides the Storage Utilization graph which is not displaying any data.

![grafik](https://user-images.githubusercontent.com/1267594/109000431-ffe6e180-76a3-11eb-9e79-da615eb12687.png)

**Comment by greenstatic** [comment]
Do you have the correct node_exporter variable selected in the top left corner of the Grafana dashboard?

**Comment by LiohMoeller** [comment]
Yes, just found it out an hour ago. Thanks.
