### ISSUE TITLE
disable auto remove config for Prometheus or exporter data of BBB

### ISSUE THREAD

**Issue by cod3r0k** [greenstatic/bigbluebutton-exporter#90]
Hi, I want to save all BBB data and I don't want to remove any history of them. What should I do now? I check my Grafana and I found that it was removed my data from 7 days ago to the first.

Thanks.

**Comment by greenstatic** [comment]
What type of installation do you have? I suspect your Prometheus volume is not being persisted. If you installed Prometheus using Docker, check when the container was last restarted - does it correlate with the oldest data you have in Grafana?

Prometheus by default (IIRC) removes data after 150 days, you can control this using the `--storage.tsdb.retention.time` flag. See the All in One Docker compose file as an example: https://github.com/greenstatic/bigbluebutton-exporter/blob/6a44d9a89028d95019231cfdaa4480b2b616e862/extras/all_in_one_monitoring/docker-compose.yaml#L29

**Comment by cod3r0k** [comment]
> What type of installation do you have? I suspect your Prometheus volume is not being persisted. If you installed Prometheus using Docker, check when the container was last restarted - does it correlate with the oldest data you have in Grafana?
> 
> Prometheus by default (IIRC) removes data after 150 days, you can control this using the `--storage.tsdb.retention.time` flag. See the All in One Docker compose file as an example:
> 
> https://github.com/greenstatic/bigbluebutton-exporter/blob/6a44d9a89028d95019231cfdaa4480b2b616e862/extras/all_in_one_monitoring/docker-compose.yaml#L29


Dear @greenstatic , I install BBB-exporter as you mentioned in this repo. You mean that I must change the Prometheus (main server) or BBB server?

I think you said that I must change the Prometheus server. Isn't it?

**Comment by greenstatic** [comment]
There are [three installation methods](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installation-type-matrix) outlined in the docs:
* Docker installation
* All in One Monitoring Stack installation
* Systemd installation

If you installed the All in One Monitoring Stack, Prometheus is included in the docker-compose and configured correctly to save metrics for up to 400 days. The other installation methods require you do install Prometheus yourself so I cannot comment on how it is configured.

So, which installation method did you use out of the aforementioned methods?

**Comment by cod3r0k** [comment]
> There are [three installation methods](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installation-type-matrix) outlined in the docs:
> 
> * Docker installation
> * All in One Monitoring Stack installation
> * Systemd installation
> 
> If you installed the All in One Monitoring Stack, Prometheus is included in the docker-compose and configured correctly to save metrics for up to 400 days. The other installation methods require you do install Prometheus yourself so I cannot comment on how it is configured.
> 
> So, which installation method did you use out of the aforementioned methods?

Thanks a lot. I installed my Prometheus from the `https://prometheus.io/docs/prometheus/latest/installation/` and then I installed the BBB-expoter and Node-exporter. Then, I config my Prometheus to gather its data from each BBB nodes.

**Comment by greenstatic** [comment]
If you blindly ran the docker command in the Prometheus installation docs, you don't have persistent data. All data is by default stored in the container. So when the container is removed, all data is lost. It is even mentioned in the docs:
> For production deployments it is highly recommended to use a named volume to ease managing the data on Prometheus upgrades.

Check the All in One docker-compose file I linked above for an example on how to create a Prometheus installation using Docker that persists your data.

Grafana does not save any metrics, it only queries Prometheus (which is a time-series database) for data. If you are experiencing data loss, your best bet is to look at Prometheus.

**Comment by cod3r0k** [comment]
Dear @greenstatic , I have multiple servers. Does the All in One docker useful for me?

**Comment by greenstatic** [comment]
You can fork the all in one docker-compose file and remove the bbb-exporter container. This will give you Prometheus and Grafana - your monitoring stack and install it on your different server. Then install bbb-exporter on each BBB host according to the `Docker installation` instruction. Finally configure your Prometheus to scrape your bbb servers.

**Comment by cod3r0k** [comment]
> remove the bbb-exporter container

Thanks, You mean that I remove bbb-exporter service as below? 
![image](https://user-images.githubusercontent.com/36899025/114197263-692a6780-9967-11eb-8f22-c4fbf29f7275.png)

**Comment by greenstatic** [comment]
correct.

**Comment by cod3r0k** [comment]
Also we doesn't need `node_exporte` container. Isn't it?

> correct.

**Comment by cod3r0k** [comment]
Is there any restriction about the Grafana's port? In separated installation, I found that it's port is 3000. But, I found 3001 in your docker-compose file. 

Also, can we use one specific URL (like as `https://example.com`) and not using any directory based on each URL (like as you wrote 'https://example.com//directory`?

**Comment by greenstatic** [comment]
1. you can leave node_exporter in, so that all infrastructure can be part of your monitoring. It is not required though.
2. [Port 3000](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installing-grafana-on-the-bigbluebutton-server)
3. Sure, your monitoring stack can be setup as you like.

**Comment by cod3r0k** [comment]
> 1. you can leave node_exporter in, so that all infrastructure can be part of your monitoring. It is not required though.
> 2. [Port 3000](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installing-grafana-on-the-bigbluebutton-server)
> 3. Sure, your monitoring stack can be setup as you like.

Thanks. You mean that I change the wrote port to 3000?

```
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.1
    network_mode: host
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
      GF_SERVER_HTTP_PORT: "3001"   ->>  '3000'
      GF_SERVER_ROOT_URL: "https://example.com/monitoring"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart: unless-stopped
```

**Comment by greenstatic** [comment]
Correct, since the container uses the host's network stack (`network_mode: host`) you should not have any other issues with network ports applying the change.

**Comment by cod3r0k** [comment]
Dear @greenstatic Thanks. I am doing this approach. It was pretty well!

But I have a problem in prometheus setup with All in one approach. Please help me at https://github.com/greenstatic/bigbluebutton-exporter/issues/92
