### ISSUE TITLE
Possibility to have user errors in monitoring

### ISSUE THREAD

**Issue by mrkeksi** [greenstatic/bigbluebutton-exporter#91]
I have already seen in a monitoring the possibility that the error codes (like 1020) of the individual user sessions were transferred to the Grafana Dashboard. Do you know a way how to do that?

Thanks for the help

**Comment by greenstatic** [comment]
I have not seen such a setup myself, however I suspect this information is available in BBB's log and then pulled into Elasticsearch or Loki - since Grafana supports both natively. If you encounter any more information I would appreciate if you could report back here.

**Comment by mrkeksi** [comment]
You're right about that. It was loki. Now I just have to figure out how to integrate it into our monitoring.

I should have just looked a little further.
https://omi-gitlab.e-technik.uni-ulm.de/kiz/bbb/config/grafana/-/blob/master/dashboards/errors.json
