### ISSUE TITLE
No CPU and Memory and Network Utilization Metrics

### ISSUE THREAD

**Issue by misisol** [greenstatic/bigbluebutton-exporter#95]
Thanks for your great project, it's working as expected. But No CPU and Memory and Network Utilization Metric are not gathered from the servers.
I've installed bigbluebutton-exporter with help of docker instruction and have not installed Netdata.
what could be the problem?

**Comment by misisol** [comment]
I've gone with All-In-One Monitoring Stack btw.

**Comment by greenstatic** [comment]
The All-in-One Monitoring stack [installs node_exporter](https://github.com/greenstatic/bigbluebutton-exporter/blob/6a44d9a89028d95019231cfdaa4480b2b616e862/extras/all_in_one_monitoring/docker-compose.yaml#L48-L61) so Netdata should not be required. 

Try changing the labels in your Grafana dashboard (top left corner). Sometimes after installation, for the first time, they glitch out a bit. It is a known bug which we haven't been able to exactly pinpoint down yet.

**Comment by greenstatic** [comment]
Make sure you also have the node_exporter flavor of the dashboard.

Here is a link to a similar issue you had: https://github.com/greenstatic/bigbluebutton-exporter/issues/94#issuecomment-833911576

**Comment by misisol** [comment]
After installing node_exporter the metrics has shown in the dashboard. thanks for your advice.

Recommendation : Please add the node_exporter installation phase in All-in-One Monitoring installation instruction.
