### ISSUE TITLE
Timeout during install, not sure how to resume

### ISSUE THREAD

**Issue by musyne** [greenstatic/bigbluebutton-exporter#97]
Hi,

I followed the all-in-one instructions on a brand new BBB Ubuntu server and I got a timeout during the "Creating grafana" step.
Now prometheus doesn't start.
I've tried deleting the bbb-monitoring folder and starting again but it's not working. I've also tried "docker system prune" to do some cleanup but it still doesn't trigger a complete reinstallation.
What can I do?

This is what happened:
`
root@ns320601:~/bbb-monitoring# sudo docker-compose up -d
Creating volume "bbb-monitoring_prometheus_data" with default driver
Creating volume "bbb-monitoring_grafana_data" with default driver
Pulling bbb-exporter (greenstatic/bigbluebutton-exporter:v0.6.0)...
v0.6.0: Pulling from greenstatic/bigbluebutton-exporter
188c0c94c7c5: Pull complete
55578f60cda7: Pull complete
bcfc1cf21055: Pull complete
9a5a622b736a: Pull complete
f96e45f99d7b: Pull complete
75b06f2485eb: Pull complete
c6644fbe5cf6: Pull complete
543bd612916e: Pull complete
Digest: sha256:bacd04474a1dd79a79e8fa7dd9e1408a8d3414f84d9f9081ba192401172bfcc7
Status: Downloaded newer image for greenstatic/bigbluebutton-exporter:v0.6.0
Pulling prometheus (prom/prometheus:v2.20.0)...
v2.20.0: Pulling from prom/prometheus
76df9210b28c: Pull complete
559be8e06c14: Pull complete
c3806e22dbf3: Pull complete
56d23a920106: Pull complete
a972397e72b5: Pull complete
9b5a09e16121: Pull complete
2225e61e06fd: Pull complete
7146c8cda861: Pull complete
9842fcf5acf9: Pull complete
0fa64066a0cb: Pull complete
12d0f59dafd4: Pull complete
7d95766f273b: Pull complete
Digest: sha256:d4ba4dd1a9ebb90916d0bfed3c204adcb118ed24546bf8dd2e6b30fc0fd2009e
Status: Downloaded newer image for prom/prometheus:v2.20.0
Pulling grafana (grafana/grafana:7.1.1)...
7.1.1: Pulling from grafana/grafana
df20fa9351a1: Pull complete
0c4618e4f645: Pull complete
14e1ee5d50ba: Pull complete
a6bb42085a9f: Pull complete
9d4cf6a0eefb: Pull complete
e713894ebec4: Pull complete
Digest: sha256:61c56f3d9551afecf9a10e9f8b30a5055ceafa581cdb397b56d3b6efe6632561
Status: Downloaded newer image for grafana/grafana:7.1.1
Pulling node_exporter (prom/node-exporter:v1.0.1)...
v1.0.1: Pulling from prom/node-exporter
86fa074c6765: Pull complete
ed1cd1c6cd7a: Pull complete
ff1bb132ce7b: Pull complete
Digest: sha256:cf66a6bbd573fd819ea09c72e21b528e9252d58d01ae13564a29749de1e48e0f
Status: Downloaded newer image for prom/node-exporter:v1.0.1
Creating prometheus ... 
Creating bbb-exporter ... 
Creating node_exporter ... 
Creating grafana       ... 

ERROR: for node_exporter  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for grafana  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for bbb-exporter  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for prometheus  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for node_exporter  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for grafana  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for bbb-exporter  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for prometheus  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@ns320601:~/bbb-monitoring# sudo docker-compose up -d
Starting prometheus    ... error
Starting node_exporter ... done
Starting bbb-exporter  ... done
Starting grafana       ... done

ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/bbb-monitoring/prometheus.yaml" to rootfs at "/etc/prometheus/prometheus.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/bbb-monitoring/prometheus.yaml" to rootfs at "/etc/prometheus/prometheus.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

`

**Comment by greenstatic** [comment]
I suspect your docker-compose.yaml is invalid. Are you sure, you downloaded the latest YAML?

**Comment by musyne** [comment]
Thanks.
My system automatically renamed the .yaml in .yml when I downloaded the files... that's what the issue.
